<a href="https://colab.research.google.com/github/bastokr/st_tanserflow/blob/main/%EB%B0%B1%ED%84%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

스칼라 값을 원소로 갖는 1차원 배열  (원소의 나열 : 숫자 문자 값 ......)


In [1]:
import tensorflow as tf
import numpy as np

py_list = [10.,20.,30.]
num_arr = np.array([10.,10.,10.])

vec1 = tf.constant(py_list, dtype=tf.float32)
vec2 = tf.constant(num_arr,  dtype=tf.float32)




랭크확인

In [ ]:
print("vec1",vec1)
print("vec2",vec2)

print(tf.rank(vec1))
print(tf.rank(vec2))

vec1 tf.Tensor([10. 20. 30.], shape=(3,), dtype=float32)
vec2 tf.Tensor([10. 10. 10.], shape=(3,), dtype=float32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)


덧셈함수

In [ ]:
add1 = tf.math.add(vec1,vec2)
print("result",add1)
print("rank",tf.rank(add1))

result tf.Tensor([20. 30. 40.], shape=(3,), dtype=float32)
rank tf.Tensor(1, shape=(), dtype=int32)


덧셈연산자

In [ ]:
add2 = vec1 + vec2
print("result:",add2)
print("rank:", tf.rank(add2))

result: tf.Tensor([20. 30. 40.], shape=(3,), dtype=float32)
rank: tf.Tensor(1, shape=(), dtype=int32)


모듈연산자