<a href="https://colab.research.google.com/github/bastokr/st_tanserflow/blob/main/%ED%96%89%EB%A0%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

행렬은 차수가 1인 벡터를 같은 축방향으로 나열 (1차원백터를 원소로 같은 다차원배열)

In [9]:
import tensorflow as tf

list_of_list = [[10,20], [30,40]]

mat1 = tf.constant(list_of_list)

print("rank",tf.rank(mat1))
print("matl:",mat1)

rank tf.Tensor(2, shape=(), dtype=int32)
matl: tf.Tensor(
[[10 20]
 [30 40]], shape=(2, 2), dtype=int32)


1차원 배열 합치기

In [10]:
vec1 = tf.constant([1,0])
vec2 = tf.constant([-1,2])


mat2 = tf.stack([vec1,vec2])

print("rank",tf.rank(mat2))

print("mat2",mat2)


rank tf.Tensor(2, shape=(), dtype=int32)
mat2 tf.Tensor(
[[ 1  0]
 [-1  2]], shape=(2, 2), dtype=int32)


연산

In [14]:
element_mul = tf.math.multiply(mat1,mat2)

print("rank",tf.rank(element_mul))

print("result",element_mul)

element_bc = tf.math.multiply(element_mul,3)

print("result",element_bc)


rank tf.Tensor(2, shape=(), dtype=int32)
result tf.Tensor(
[[ 10   0]
 [-30  80]], shape=(2, 2), dtype=int32)
result tf.Tensor(
[[ 30   0]
 [-90 240]], shape=(2, 2), dtype=int32)


형태 변환

In [17]:
import tensorflow as tf
tensor = tf.constant(range(0,24))
print(tensor)

tensor1 = tf.reshape(tensor,[3,8])

print(tensor1)

tf.Tensor([ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23], shape=(24,), dtype=int32)
tf.Tensor(
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]], shape=(3, 8), dtype=int32)
